Ajout connexion signal nouvelleDonnee
btssn-lasalle-84/eco-classroom-2024 pull request #21
Opened 2024-05-26 17:57 UTC by TVIGNAL

2024-05-26 18:11 UTC, tvaira requested changes

2024-05-26 18:11 UTC, tvaira commented on eco-classroom-desktop/ihmecoclassroom.cpp
> +            SLOT(afficherNouvelleDonnee(QString, QString, QString)));
Tu le déclares dans la classe `IHMEcoClassroom` avec la signature suivante : `void afficherNouvelleDonnee(QString nomSalleEco, QString typeDonnee, QString donnee);`

Ensuite tu le définis :

```cpp
void IHMEcoClassroom::afficherNouvelleDonnee(QString nomSalleEco, QString typeDonnee, QString donnee)
{
    qDebug() << Q_FUNC_INFO << "nomSalleEco" << nomSalleEco << "typeDonnee" << typeDonnee << "donnee"
                 << donnee;
}
```

Tu ne peux pas faire plus pour l'instant car tu n'as pas encore prévu de fenêtre d'affichage.

2024-05-26 18:15 UTC, TVIGNAL commented on eco-classroom-desktop/ihmecoclassroom.cpp
> +            SLOT(afficherNouvelleDonnee(QString, QString, QString)));
D'accord je vous remercie, ça serait possible d'avoir des TODO car je ne sais pas comment démarrer pour le reste...

2024-05-26 19:08 UTC, tvaira commented on eco-classroom-desktop/ihmecoclassroom.cpp
> +            SLOT(afficherNouvelleDonnee(QString, QString, QString)));
Tu peux déjà faire les états pour les afficher dans le tableau sur le principe qui a été fait pour les indices.

2024-05-29 13:32 UTC, tvaira approved these changes

2024-05-29 13:34 UTC, merged