Ajout fonctionnalité de filtrage
btssn-lasalle-84/eco-classroom-2024 pull request #22
Opened 2024-05-30 09:12 UTC by TVIGNAL

2024-05-30 10:25 UTC, tvaira requested changes

2024-05-30 10:25 UTC, tvaira commented on eco-classroom-desktop/ihmecoclassroom.h
> +    QVBoxLayout*  mainLayout;
`mainLayout` !!! je saute de joie !

Je t'ai mis les TODOs

2024-05-31 07:15 UTC, TVIGNAL commented on eco-classroom-desktop/ihmecoclassroom.h
> +    QVBoxLayout*  mainLayout;
Je ne comprends pas ou placer le mainLayout sachant que je l'utilise dans 3 méthodes différentes

2024-06-01 10:14 UTC, TVIGNAL commented
Je pensais fermer cette branche et mettre de côté le filtrage pour le moment, pour me concentrer sur la visualisation spécifique des salles, je sais pas ce que vous en pensez

2024-06-01 12:28 UTC, tvaira commented
> Je pensais fermer cette branche et mettre de côté le filtrage pour le moment, pour me concentrer sur la visualisation spécifique des salles, je sais pas ce que vous en pensez

Tu fusionnes et tu feras une branche plus tard pour finir le filtrage.

2024-06-01 12:39 UTC, merged